// server.ini schema and IO for llama.cpp-framework.

use std::fs;
use std::io;

use crate::ini;
use crate::paths;

#[derive(Debug, Clone, Default)]
pub struct ServerConfig {
    pub port: Option<i32>,
    pub hostname: Option<String>,
    pub mlock: Option<bool>,
    pub threads: Option<i32>,
    pub cache_reuse: Option<i32>,
    pub threads_batch: Option<i32>,
    pub models_max: Option<i32>,
    pub models_dir: Option<String>,
    /// GPU device(s) for the main model, e.g. "CUDA0" (--device). Empty/None =
    /// let llama.cpp use all detected devices. Pinning to one device avoids
    /// splitting across an iGPU or a duplicate Vulkan view of the same GPU.
    pub device: Option<String>,
}

pub fn default_models_dir() -> String {
    paths::home_dir()
        .join(".llama.cpp")
        .join("models")
        .to_string_lossy()
        .into_owned()
}

pub fn load() -> ServerConfig {
    let path = paths::server_ini();
    let keys = ini::read_section(&path, "Server");
    ServerConfig {
        port: keys.get("Port").and_then(|v| ini::parse_int(v)),
        hostname: keys.get("Hostname").cloned(),
        mlock: keys.get("Mlock").and_then(|v| ini::parse_bool(v)),
        threads: keys.get("Threads").and_then(|v| ini::parse_int(v)),
        cache_reuse: keys.get("CacheReuse").and_then(|v| ini::parse_int(v)),
        threads_batch: keys.get("ThreadsBatch").and_then(|v| ini::parse_int(v)),
        models_max: keys.get("ModelsMax").and_then(|v| ini::parse_int(v)),
        models_dir: keys.get("ModelsDir").cloned(),
        device: keys.get("Device").cloned().filter(|s| !s.trim().is_empty()),
    }
}

pub fn save(cfg: &ServerConfig) -> io::Result<()> {
    let port = cfg.port.unwrap_or(8080);
    let hostname = cfg.hostname.as_deref().unwrap_or("localhost");
    let mlock = cfg.mlock.unwrap_or(true);

    let models_dir = cfg
        .models_dir
        .clone()
        .filter(|s| !s.is_empty())
        .unwrap_or_else(default_models_dir);

    let threads_line = match cfg.threads {
        Some(n) if n > 0 => format!("Threads = {n}"),
        _ => "; Threads = 12  ; optional override; auto-detected if commented"
            .to_string(),
    };

    let cache_reuse_line = match cfg.cache_reuse {
        Some(n) => format!("CacheReuse = {n}"),
        None => "; CacheReuse = 256  ; minimum chunk size for prompt cache reuse (--cache-reuse)"
            .to_string(),
    };

    let threads_batch_line = match cfg.threads_batch {
        Some(n) if n > 0 => format!("ThreadsBatch = {n}"),
        _ => "; ThreadsBatch = 12  ; optional override; auto-detected if commented"
            .to_string(),
    };

    let models_max_line = match cfg.models_max {
        Some(n) if n != 1 => format!("ModelsMax = {n}"),
        _ => "; ModelsMax = 2  ; uncomment to allow N models resident at once (0 = unlimited; runtime default if unset: 1)".to_string(),
    };

    let device_line = match cfg.device.as_deref().map(str::trim) {
        Some(d) if !d.is_empty() => format!("Device = {d}"),
        _ => "; Device = CUDA0  ; pin the main model to one GPU (--device); blank = all detected devices"
            .to_string(),
    };

    let mlock_lit = if mlock { "true" } else { "false" };

    let body = format!(
        "; Generated by llama-cpp-config.
;
; llama-server runtime configuration (machine-wide).
; Per-model knobs live in presets.ini.

[Server]
Port = {port}
Hostname = {hostname}
Mlock = {mlock_lit}
{threads_line}
{cache_reuse_line}
{threads_batch_line}
{models_max_line}
{device_line}

; ModelsDir: root directory. Models are scanned from ModelsDir/models/,
; mmproj projection files from ModelsDir/mmprojs/, MTP/draft heads from ModelsDir/mtps/.
ModelsDir = {models_dir}
"
    );

    let path = paths::server_ini();
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    if !models_dir.is_empty() {
        let _ = fs::create_dir_all(&models_dir);
    }
    fs::write(&path, body)
}
