//! settings.ini schema and IO — the configurator's OWN settings.
//!
//! Not to be confused with server.ini (`server_cfg.rs`): every key there maps
//! to a llama-server flag or launch-env value and rides the full per-field
//! recipe (CLI `server set`, `runstate::server_args`, …). The keys here
//! configure llama-cpp-config itself — they never reach a llama-server command
//! line — so they live in their own file with none of that machinery.
//!
//! Note the one Settings-tab toggle that is deliberately NOT here: "Start with
//! Windows" is the HKCU Run registry entry itself (`startup.rs`) — mirroring it
//! into this file would only add a copy that Task Manager's Startup panel can
//! silently desync.

use std::fs;
use std::io;

use crate::ini;
use crate::paths;

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Settings {
    /// Start llama-server automatically when the GUI launches (any launch, not
    /// just the logon one). `false` when unset — the framework default.
    pub start_server_on_launch: bool,
}

pub fn load() -> Settings {
    from_keys(&ini::read_section(&paths::settings_ini(), "Settings"))
}

/// Parse the `[Settings]` key/value map. Split out of `load()` so the
/// round-trip test can run against `render()`'s output without touching the
/// real config path (mirroring `server_cfg::from_keys`).
fn from_keys(keys: &std::collections::BTreeMap<String, String>) -> Settings {
    Settings {
        start_server_on_launch: keys
            .get("StartServerOnLaunch")
            .and_then(|v| ini::parse_bool(v))
            .unwrap_or(false),
    }
}

pub fn save(cfg: &Settings) -> io::Result<()> {
    let path = paths::settings_ini();
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    ini::atomic_write(&path, &render(cfg))
}

/// Render the whole settings.ini body. Like server.ini, the file is fully
/// generated and self-documents its keys.
fn render(cfg: &Settings) -> String {
    let autostart_lit = if cfg.start_server_on_launch {
        "true"
    } else {
        "false"
    };
    format!(
        "; Generated by llama-cpp-config.
;
; Settings of the configurator itself (Settings tab). llama-server's runtime
; configuration lives in server.ini; per-model knobs in presets.ini.

[Settings]
; StartServerOnLaunch: start llama-server automatically whenever
; llama-cpp-config launches. A no-op when the server is already running.
StartServerOnLaunch = {autostart_lit}
"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    /// `render` → parse-back through the real INI reader — a key-name typo
    /// between `from_keys` and the writer fails here (same guard shape as
    /// server_cfg's round-trip).
    fn round_trip(cfg: &Settings) -> Settings {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("settings.ini");
        std::fs::write(&path, render(cfg)).unwrap();
        from_keys(&ini::read_section(&path, "Settings"))
    }

    #[test]
    fn both_states_round_trip_through_ini() {
        for on in [false, true] {
            let cfg = Settings {
                start_server_on_launch: on,
            };
            assert_eq!(round_trip(&cfg), cfg);
        }
    }

    #[test]
    fn missing_file_or_key_reads_as_default_off() {
        assert!(!from_keys(&Default::default()).start_server_on_launch);
    }
}
