# CMake cache definitions for the llama.cpp build, read by 02-build.ps1.
#
# This is the CHECKED-IN half of the configure line: the options that say WHAT
# the framework builds (which backends, which features, release rather than
# dev), identical on every machine. The other half, everything derived from
# THIS machine (compiler and linker paths, GPU targets, the OpenSSL root, the
# Vulkan SDK, the HIP header workaround, the sccache launchers, build type
# and job count), is generated by 01-configure.ps1 into
# build\config-build.psd1 and assembled by 02-build.ps1, which also owns the
# `-U` unsets that clear stale cache entries.
#
# Every entry is one `NAME=VALUE` (or `NAME:TYPE=VALUE`) string, passed to
# cmake verbatim as `-DNAME=VALUE`, in this order. A list rather than a
# hashtable so the order is stable and each option can carry its own reason.
# An entry that does not look like NAME[:TYPE]=VALUE fails the build before
# cmake sees it. Note these are CACHE entries: on an existing build dir a value
# removed from this list keeps its cached value (the cmake default is only the
# default for a FRESH cache), so to retire an option, set it explicitly to the
# value you want rather than deleting the line, or wipe build\llama.cpp-cmake.
@{
    # Single-config, parallel, what llama.cpp's own CI uses.
    Generator = 'Ninja'

    Defines = @(
        # ── ggml ──────────────────────────────────────────────────────
        # No -march=native, and no global -march at all (02-build.ps1 passes
        # none): the binaries ship to other machines, and the ISA-specific
        # code is the ggml-cpu variants below, each compiled with its own -m
        # flags. A global -march would leak into the baseline variants and
        # defeat them (through v1.14.0 the framework passed -march=x86-64-v3,
        # so ggml-cpu-x64.dll was an AVX2 build). Everything outside those
        # variants is dispatch and bookkeeping and stays at the compiler's
        # default baseline, as in upstream's own release binaries.
        'GGML_NATIVE=OFF'
        # Backends as separately loadable DLLs (ggml-cuda.dll, ggml-hip.dll,
        # ggml-vulkan.dll, the ggml-cpu variants), so a machine missing one
        # vendor's runtime skips that backend instead of failing to load
        # llama-server at all.
        'GGML_BACKEND_DL=ON'
        # One ggml-cpu DLL per ISA level (x64, sse42, sandybridge, haswell,
        # skylakex, zen4, ...), the best one the CPU supports picked at
        # runtime by ggml's feature score.
        'GGML_CPU_ALL_VARIANTS=ON'
        # The three GPU backends this framework exists for.
        'GGML_CUDA=ON'
        'GGML_VULKAN=ON'
        'GGML_HIP=ON'

        # ── optimisation ──────────────────────────────────────────────
        # Link-time optimisation, for the targets under ggml/src only: that
        # is where llama.cpp sets CMAKE_INTERPROCEDURAL_OPTIMIZATION when this
        # is ON (gated on its own check_ipo_supported), so ggml-base, every
        # ggml-cpu variant, ggml-vulkan and the host half of ggml-hip get
        # -flto=thin and lld-link does the LTO. It does NOT reach ggml-cuda
        # (nvcc: CMake drives no IPO flag for it, the CUDA lines are
        # unchanged) nor llama / common / llama-server, which sit outside that
        # directory scope; a global CMAKE_INTERPROCEDURAL_OPTIMIZATION would
        # cover those but also hits the CUDA target, so it is not passed.
        # Cost: bitcode objects, so codegen moves into the links (slower
        # links, parallel by default across the physical cores in lld-link;
        # sccache still caches the compiles). On since 2026-09-07,
        # together with dropping the global -march: measure it with the
        # Benchmark tab rather than assuming a gain.
        'GGML_LTO=ON'

        # ── llama.cpp ─────────────────────────────────────────────────
        # llama.cpp calls itself "<X.Y.Z>-dev" unless told otherwise: its
        # CMakeLists.txt defaults LLAMA_BUILD_IS_DEV to ON, with "set this to
        # OFF when making a release from a release tag (vX.Y.Z)". That is
        # exactly and only what 02-build.ps1 checks out (its tag selection
        # admits nothing else), so the -dev suffix would be a lie here. The
        # value rides a compile definition on the `llama` target and reaches
        # `llama-server --version`, and from there the configurator's footer
        # badge: `0.4.0 · b10809` rather than `0.4.0-dev · b10809`. Flipping it
        # recompiles that target, not ggml's CUDA/HIP kernels.
        'LLAMA_BUILD_IS_DEV=OFF'
        # The chat UI llama-server serves is the framework's frontend, and it
        # is EMBEDDED at build time. Upstream flipped this default to OFF in
        # v0.4.0 (#27706): OFF means the UI is no longer built from the
        # checked-out sources with npm but DOWNLOADED from the ggml-org/llama-ui
        # HuggingFace bucket during configure (keyed by build number, `latest`
        # as the fallback), and when that download fails the build goes on
        # WITHOUT a UI, on nothing louder than a cmake warning. ON keeps the
        # UI coming from the same tag as the server (node + npm are already
        # prerequisites here: resources\generate-llama-ico.mjs needs them).
        # 02-build.ps1 additionally refuses to finish a build whose UI did not
        # get embedded, whichever path produced it.
        'LLAMA_BUILD_UI=ON'
        # The fallback behind the line above, stated rather than inherited: if
        # the npm build fails, the prebuilt UI for this build number is fetched
        # instead (same version, so still the tag's own UI). Set to OFF to make
        # an npm failure surface as a missing UI, which the guard in
        # 02-build.ps1 then turns into a build failure.
        'LLAMA_USE_PREBUILT_UI=ON'
    )
}
