# Open WebUI configuration.
#
# Writes %LOCALAPPDATA%\llama.cpp\config\webui.psd1. Prompts for Port and
# Hostname (Enter accepts the default). NSIS calls this with -NonInteractive
# plus values from the install-time custom page.

[CmdletBinding()]
param(
    [int]$Port,
    [string]$Hostname,
    [switch]$NonInteractive
)

$ErrorActionPreference = 'Stop'

$configDir = Join-Path $env:LOCALAPPDATA "llama.cpp\config"
$webuiPath = Join-Path $configDir "webui.psd1"

New-Item -ItemType Directory -Path $configDir -Force | Out-Null

$cur = if (Test-Path $webuiPath) { Import-PowerShellDataFile -Path $webuiPath } else { @{} }

function Read-IntDefault {
    param([string]$Prompt, $Default, [int]$Min = 1, [int]$Max = 65535)
    while ($true) {
        $reply = Read-Host "$Prompt [$Default]"
        if (-not $reply) { return $Default }
        [int]$parsed = 0
        if ([int]::TryParse($reply, [ref]$parsed) -and $parsed -ge $Min -and $parsed -le $Max) {
            return $parsed
        }
        Write-Host "  Invalid value." -ForegroundColor Yellow
    }
}

$portVal = if ($PSBoundParameters.ContainsKey('Port')     -and $Port -gt 0) { $Port }     elseif ($cur.Port)     { $cur.Port }     else { 3000 }
$hostVal = if ($PSBoundParameters.ContainsKey('Hostname') -and $Hostname)   { $Hostname } elseif ($cur.Hostname) { $cur.Hostname } else { 'localhost' }

if (-not $NonInteractive) {
    Write-Host ""
    Write-Host "── Open WebUI configuration ──" -ForegroundColor Cyan
    Write-Host ""

    $portVal = Read-IntDefault "Port" $portVal 1 65535

    Write-Host ""
    Write-Host "Network exposure:" -ForegroundColor Cyan
    Write-Host "  [1] localhost only"
    Write-Host "  [2] all interfaces (LAN)"
    $defaultBind = if ($hostVal -eq '0.0.0.0') { 2 } else { 1 }
    $bindReply = Read-IntDefault "Bind to" $defaultBind 1 2
    $hostVal = if ($bindReply -eq 2) { '0.0.0.0' } else { 'localhost' }
}

$hostEsc = $hostVal -replace "'", "''"
$content = @"
@{
    # Generated by config-webui.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm')

    Port     = $portVal
    Hostname = '$hostEsc'
}
"@

Set-Content -Path $webuiPath -Value $content -Encoding utf8NoBOM

if (-not $NonInteractive) {
    Write-Host ""
    Write-Host "Configuration written to:" -ForegroundColor Green
    Write-Host "  $webuiPath"
    Write-Host ""
}
